### ISSUE TITLE
Objects in hamburger menu.

### ISSUE THREAD

**Issue by QW3w** [ThinkAloudProject/ThinkAloudIssues#1]
Objects in hamburger meny doesn't look correctly. I think, that 'll be better, if you will combo objects in **groups icon-text**.

That will solve it, because objects are not connected to each other. Maybe, you need to make limiters.

**Comment by Milk-Cool** [comment]
![image](https://user-images.githubusercontent.com/43724263/183244093-c3b640c1-7923-4dda-ba7d-fde14bdb4203.png)
It seems like this might be a fine solution, what do you think?

**Comment by QW3w** [comment]
Yeah, cool, maybe $ should be closer to "помочь".

**Comment by Milk-Cool** [comment]
Maybe. I'll try moving it a bit
