### ISSUE TITLE
Not fixed problem with hyphenation. 

### ISSUE THREAD

**Issue by QW3w** [ThinkAloudProject/ThinkAloudIssues#2]
![image](https://user-images.githubusercontent.com/90787581/183244270-b2ca2e5e-72bb-4c56-91be-4ba965aa8179.png)
Many words have a problem with a hyphenation.

**Comment by Milk-Cool** [comment]
It's fixed already, just wait for an update
![image](https://user-images.githubusercontent.com/43724263/183245689-60331b0c-acd5-4718-84d9-ea1d9d40396c.png)

**Comment by QW3w** [comment]
Ok!
